import Navbar from "../components/Navbar/Navbar";
import "./Recommendations.css";

import developerProfile from "../assets/profiles/developer.png";

export default function Recommendations() {
  return (
    <>
      <Navbar profileImage={developerProfile} activeProfile="developer" />

      <section className="recommendations-page">
        <div className="recommendation-card">
          {/* Header */}
          <div className="rec-header">
            <img
              src="https://i.pravatar.cc/150?img=32"
              alt="Emily T."
              className="rec-avatar"
            />

            <div>
              <h2 className="rec-name">Emily T.</h2>
              <p className="rec-role">Project Head at Outliner</p>
              <span className="rec-date">October 24, 2025</span>
            </div>
          </div>

<div className="rec-body">
  <p>
    <strong>It is with great pleasure</strong> that I recommend Shivam for
    his work with us at Outliner, where he contributed as an AI expert focused
    on shaping the future of interfaces. Shivam joined our team after his
    standout project in an Outliner-hosted hackathon, where his ability to
    combine technical depth with strong design intuition was immediately
    evident.
  </p>

  <p>
    During his time at Outliner, Shivam played a key role in refining UI code
    generated by our AI models, transforming it into modern, intuitive, and
    user-friendly interfaces. His work consistently elevated raw model outputs
    into polished experiences that aligned with real user expectations.
  </p>

  <p>
     Shivam demonstrated a strong understanding of both AI-driven systems and
    human-centered design, often pushing interface quality beyond current
    industry benchmarks. He worked with professionalism, curiosity, and a
    proactive mindset throughout our collaboration.
  </p>

  <p className="rec-highlight">
     I confidently recommend Shivam for roles at the intersection of AI,
    product, and user experience.
  </p>
</div>

        </div>
      </section>
    </>
  );
}
